import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';

export const metadata: Metadata = { title: 'About', description: 'Meet PowerTrust Energy Limited, an integrated electrical, solar and plumbing solutions company.' };

const principles = [
  ['01', 'Trust through clarity', 'Straight answers, practical scopes and no unnecessary complexity.'],
  ['02', 'Work that lasts', 'We prioritise sound design, quality materials and maintainable installations.'],
  ['03', 'Safety by default', 'Every system is approached with testing, protection and responsible practices in mind.'],
  ['04', 'Knowledge shared', 'Our training arm turns field experience into useful, employable skills.'],
];

export default function AboutPage() {
  return <main>
    <section className="relative overflow-hidden bg-[#061a33] py-24 text-white md:py-36"><div className="absolute inset-0 brand-grid opacity-70" /><div className="absolute -right-24 top-0 h-96 w-96 rounded-full bg-[#0876d1]/25 blur-3xl" /><div className="site-shell relative"><span className="inline-flex rounded-full border border-white/15 bg-white/5 px-4 py-2 text-xs font-extrabold uppercase tracking-[.17em] text-[#8bd338]">About PowerTrust</span><h1 className="display-title mt-7 max-w-5xl text-3xl md:text-5xl">Built on skill.<br />Measured by trust.</h1><p className="mt-8 max-w-2xl text-base leading-7 text-slate-300 md:text-lg">We help people and organisations run safer, smarter spaces through reliable technical systems while training the next generation to do the same.</p></div></section>

    <section className="bg-white py-24 md:py-32"><div className="site-shell grid items-center gap-14 lg:grid-cols-[1.05fr_.95fr]"><div><span className="eyebrow">Our company</span><h2 className="display-title mt-5 text-3xl text-[#071b35] md:text-5xl">Essential infrastructure, handled as one connected system.</h2><p className="mt-7 text-base leading-7 text-slate-600">PowerTrust Energy Limited delivers electrical, renewable energy and plumbing services for residential and commercial environments. Bringing these disciplines together means better coordination, fewer gaps and a clearer path from assessment to handover.</p><p className="mt-5 leading-7 text-slate-600">Our approach is practical: understand the requirement, specify responsibly, execute neatly and remain available after the job is done.</p></div><div className="relative overflow-hidden rounded-[2rem]"><Image src="/powertrust-hero.png" alt="PowerTrust technical professionals" width={1536} height={864} className="aspect-[4/5] w-full object-cover object-[72%_center]" /><div className="absolute bottom-5 left-5 right-5 rounded-2xl bg-white/90 p-5 backdrop-blur"><strong className="block text-xl text-[#071b35]">Integrated expertise</strong><span className="mt-1 block text-sm text-slate-600">Electrical · Solar · Plumbing · Training</span></div></div></div></section>

    <section className="bg-[#eef4f9] py-24 md:py-32"><div className="site-shell"><div className="grid gap-8 lg:grid-cols-2"><div><span className="eyebrow">What guides us</span><h2 className="display-title mt-5 max-w-xl text-3xl text-[#071b35] md:text-5xl">Good systems begin with good decisions.</h2></div><p className="max-w-xl self-end text-base leading-7 text-slate-600">Technology changes. The fundamentals do not: listen carefully, plan responsibly, work safely and leave the customer with something dependable.</p></div><div className="mt-14 grid gap-px overflow-hidden rounded-[2rem] bg-slate-200 sm:grid-cols-2">{principles.map(([n,t,d]) => <div key={n} className="bg-white p-7 md:p-10"><span className="text-xs font-extrabold tracking-[.18em] text-[#0876d1]">{n}</span><h3 className="mt-8 text-xl font-extrabold text-[#071b35]">{t}</h3><p className="mt-3 leading-7 text-slate-600">{d}</p></div>)}</div></div></section>

    <section className="bg-white py-24"><div className="site-shell grid gap-6 md:grid-cols-3"><div className="rounded-[2rem] bg-[#071b35] p-8 text-white"><span className="text-xs font-extrabold uppercase tracking-wider text-[#8bd338]">Mission</span><p className="mt-6 text-xl font-bold leading-9">Deliver technical solutions people can rely on and skills people can build a future with.</p></div><div className="rounded-[2rem] border border-slate-200 p-8"><span className="text-xs font-extrabold uppercase tracking-wider text-[#0876d1]">Vision</span><p className="mt-6 text-xl font-bold leading-9 text-[#071b35]">A future where dependable infrastructure and practical technical talent are within reach.</p></div><div className="rounded-[2rem] bg-[#65bd00] p-8 text-[#061a33]"><span className="text-xs font-extrabold uppercase tracking-wider">Next step</span><p className="mt-6 text-xl font-bold leading-9">Bring us your project or begin your own technical journey.</p><Link href="/register" className="mt-7 inline-block font-extrabold">Explore training →</Link></div></div></section>
  </main>;
}
