import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = { title: 'Solutions & Training', description: 'Electrical, solar and plumbing services and practical training from PowerTrust Energy Limited.' };

const disciplines = [
  { id:'electrical', n:'01', name:'Electrical', color:'#0876d1', intro:'Dependable power distribution for safe, functional spaces.', services:['Residential and commercial wiring','Distribution boards and circuit protection','Fault detection and corrective maintenance','Load assessment and system upgrades'], training:['Wiring principles and safe tool handling','Circuit breakers, consumer units and testing','Fault-finding on practical installation boards','Standards, documentation and job-site safety'] },
  { id:'solar', n:'02', name:'Solar energy', color:'#65bd00', intro:'Right-sized clean energy systems for greater independence.', services:['Energy audits and system sizing','Solar PV, inverter and battery installation','Hybrid and off-grid system configuration','Maintenance and performance checks'], training:['PV technology and energy calculations','Panel orientation, mounting and wiring','Battery, inverter and controller setup','Troubleshooting and preventive maintenance'] },
  { id:'plumbing', n:'03', name:'Plumbing', color:'#ff7a00', intro:'Clean, durable water and sanitary systems that perform.', services:['Water supply and distribution','Sanitary fittings and drainage','Leak detection and repairs','Pressure testing and maintenance'], training:['PVC, PPR and metal pipework','Fixtures, valves and water-flow control','Drainage planning and troubleshooting','Pressure tests, repairs and site practice'] },
];

export default function SolutionsPage() {
  return <main>
    <section className="relative overflow-hidden bg-[#061a33] py-24 text-white md:py-36"><div className="absolute inset-0 brand-grid opacity-70" /><div className="site-shell relative grid gap-10 lg:grid-cols-[1.25fr_.75fr] lg:items-end"><div><span className="inline-flex rounded-full border border-white/15 bg-white/5 px-4 py-2 text-xs font-extrabold uppercase tracking-[.17em] text-[#8bd338]">Solutions & skills</span><h1 className="display-title mt-7 text-3xl md:text-5xl">We install it.<br />We teach it.</h1></div><p className="text-base leading-7 text-slate-300">The same practical disciplines that shape our service work also shape our training: real systems, real tools and sound technical judgment.</p></div></section>

    <section className="bg-white py-20"><div className="site-shell flex flex-wrap gap-3">{disciplines.map(d=><a href={`#${d.id}`} key={d.id} className="rounded-full border border-slate-200 px-5 py-3 text-sm font-extrabold text-[#071b35] transition hover:border-[#0876d1] hover:text-[#0876d1]">{d.n} · {d.name}</a>)}</div></section>

    {disciplines.map((d,i)=><section id={d.id} key={d.id} className={`${i%2?'bg-[#eef4f9]':'bg-white'} scroll-mt-24 py-24 md:py-32`}><div className="site-shell"><div className="grid gap-10 lg:grid-cols-[.72fr_1.28fr]"><div><div className="flex items-center gap-4"><span className="text-xs font-extrabold tracking-[.2em] text-slate-400">{d.n}</span><span className="h-1 w-14 rounded-full" style={{background:d.color}} /></div><h2 className="display-title mt-7 text-4xl text-[#071b35] md:text-5xl">{d.name}</h2><p className="mt-6 max-w-md text-base leading-7 text-slate-600">{d.intro}</p><a href={`https://wa.me/2348039375634?text=${encodeURIComponent(`Hello PowerTrust, I need help with a ${d.name.toLowerCase()} project.`)}`} target="_blank" rel="noreferrer" className="mt-8 inline-block rounded-full bg-[#071b35] px-6 py-3.5 text-sm font-extrabold text-white">Discuss a project</a></div><div className="grid gap-5 sm:grid-cols-2"><div className="rounded-[2rem] border border-slate-200 bg-white p-7 md:p-9"><span className="text-xs font-extrabold uppercase tracking-[.18em]" style={{color:d.color}}>Professional services</span><ul className="mt-7 space-y-4">{d.services.map(x=><li key={x} className="flex gap-3 text-sm font-semibold leading-6 text-slate-700"><span className="mt-2 h-2 w-2 shrink-0 rounded-full" style={{background:d.color}} />{x}</li>)}</ul></div><div className="rounded-[2rem] bg-[#071b35] p-7 text-white md:p-9"><span className="text-xs font-extrabold uppercase tracking-[.18em] text-[#8bd338]">Training outcomes</span><ul className="mt-7 space-y-4">{d.training.map(x=><li key={x} className="flex gap-3 text-sm font-semibold leading-6 text-slate-200"><span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-[#8bd338]" />{x}</li>)}</ul><Link href={`/register?type=${d.name==='Solar energy'?'Solar':d.name}` as any} className="mt-8 inline-block font-extrabold text-[#8bd338]">Train in {d.name} →</Link></div></div></div></div></section>)}

    <section className="bg-[#65bd00] py-24 text-[#061a33]"><div className="site-shell grid items-end gap-10 lg:grid-cols-[1fr_auto]"><div><span className="text-xs font-extrabold uppercase tracking-[.18em]">Practical training</span><h2 className="display-title mt-4 max-w-4xl text-3xl md:text-5xl">Choose 4, 8 or 12 months. Build a skill for life.</h2><p className="mt-6 max-w-2xl text-base leading-7">Start with 60% tuition and complete the balance before graduation. Every track combines guided instruction, workshop practice and project exposure.</p></div><Link href="/register" className="rounded-full bg-[#061a33] px-8 py-4 text-sm font-extrabold text-white">Register now →</Link></div></section>
  </main>;
}
